.libPaths(c("C:/Users/ale097/Data School/Packages"))
library(tidyverse)
read_csv("data/gapminder.csv")
gapminder <- read_csv("data/gapminder.csv")
select(gapminder, country, year, pop)
gapminderfiltered <- select(gapminder, country, year, pop)
filter(gapminderfiltered, country == "Australia")
australia <- filter(gapminderfiltered, country == "Australia")
select(filter(gapminder, country =="Australia"), country, year, pop)
filter(select(gapminder, country, year, pop), country == "Australia")
